//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProviderFactoriesLab {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DB : global::System.Configuration.ApplicationSettingsBase {
        
        private static DB defaultInstance = ((DB)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DB())));
        
        public static DB Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSqlLocalDB;AttachDbFilename=|DataDirectory|\\PUBS.MDF;Inte" +
            "grated Security=True;Connect Timeout=30")]
        public string PubsConnStr {
            get {
                return ((string)(this["PubsConnStr"]));
            }
        }
    }
}
